services:
  backend:
    build:
      context: ./backend
    container_name: geowatch-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: geowatch-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm start && echo 'Frontend is accessible at http://localhost:3000'"

  redis:
    image: redis:6-alpine
    container_name: geowatch-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
